version: '3.8'

services:
  db:
    image: postgres
    container_name: pastebin_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: pastebindb
    ports:
      - "54321:5432"
  django:
    container_name: django
    build:
      context: ./Pastebin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Pastebin:/usr/src/app/
    ports:
      - "8001:8000"
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
