# Generated by Django 4.2.5 on 2023-10-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIService', '0002_text_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='content',
        ),
    ]
